import numpy as np
from numpy.typing import NDArray
from numpy.random import RandomState


class KMeans:
    def __init__(
            self,
            n_clusters=3,
            max_iter=300,
            tol=1e-4,
            random_state: int | RandomState | None = None,
    ):
        self.n_clusters = n_clusters
        self.max_iter = max_iter
        self.tol = tol
        self.random_state = (
            random_state
            if isinstance(random_state, np.random.RandomState)
            else np.random.RandomState(seed=random_state)
        )
        self.cluster_centers_ = None
        self.labels_ = None
        self.inertia_ = None

    def _initialize_centroids(self, X):
        self._random_centroid_initialization(X)

    def _random_centroid_initialization(self, X: NDArray[np.floating]):
        n_samples = X.shape[0]
        init_indices = self.random_state.choice(
            n_samples, size=self.n_clusters, replace=False
        )
        self.cluster_centers_ = X[init_indices]

        return self

    def _assign_labels(self, X: NDArray[np.floating]):
        """Generated by Calude Code"""
        # X:                (n_samples, n_features)
        # cluster_centers_: (n_clusters, n_features)
        # diff:             (n_samples, n_clusters, n_features)  via broadcasting
        diff = X[:, np.newaxis, :] - self.cluster_centers_[np.newaxis, :, :]
        distances = np.sqrt((diff ** 2).sum(axis=2))  # (n_samples, n_clusters)
        return np.argmin(distances, axis=1)

    def _update_centroids(self, X: NDArray[np.floating], labels: NDArray):
        for label in range(self.n_clusters):
            mask = labels == label
            if mask.sum() == 0:
                # Reinitialize to a random point
                self.cluster_centers_[label] = X[self.random_state.randint(0, len(X))]
            else:
                self.cluster_centers_[label] = X[mask].mean(axis=0)

    def _compute_inertia(self, X: NDArray[np.floating], labels: NDArray) -> float:
        """
        Compute inertia (sum of squared distances from each point to its assigned centroid).

        Args:
            X: numpy array of shape (n_samples, n_features)
            labels: numpy array of shape (n_samples,) with cluster assignments

        Returns:
            inertia: float
        """
        centroids = self.cluster_centers_[labels]  # (n_samples, n_features)
        diff = X - centroids  # (n_samples, n_features)
        return float((diff ** 2).sum())

    def fit(self, X):
        """
        Fit the K-Means model to the data.

        Args:
            X: numpy array of shape (n_samples, n_features)

        Returns:
            self
        """
        if self.n_clusters > X.shape[0]:
            raise ValueError(
                f"n_clusters ({self.n_clusters}) cannot exceed n_samples ({X.shape[0]})"
            )

        self._initialize_centroids(X)
        labels = None
        for epoch in range(1, self.max_iter + 1):
            # Assign point to a cluster
            labels = self._assign_labels(X)
            prev_centers = self.cluster_centers_.copy()

            # Update centroids
            self._update_centroids(X, labels)

            if (
                    np.max(np.linalg.norm(self.cluster_centers_ - prev_centers, axis=1))
                    < self.tol
            ):
                break

        self.labels_ = labels
        self.inertia_ = self._compute_inertia(X, self.labels_)
        return self

    def predict(self, X):
        """
        Predict cluster labels for new data points.

        Args:
            X: numpy array of shape (n_samples, n_features)

        Returns:
            numpy array of shape (n_samples,) with cluster labels (integers 0 to n_clusters-1)
        """
        if self.cluster_centers_ is None:
            raise ValueError("Model is not fitted yet. Call fit() first.")

        return self._assign_labels(X)


class KMeansPlusPlus(KMeans):
    def _init_centroids_plusplus(self, X: NDArray[np.floating]):
        n_samples = X.shape[0]

        # Pick first centroid uniformly at random
        first_idx = self.random_state.randint(0, n_samples)
        self.cluster_centers_ = X[first_idx][np.newaxis, :]  # (1, n_features)

        # Pick remaining centroids
        for _ in range(1, self.n_clusters):
            # Distance from each point to its nearest already-chosen centroid
            diff = X[:, np.newaxis, :] - self.cluster_centers_[np.newaxis, :, :]
            sq_distances = (diff ** 2).sum(axis=2)  # (n_samples, k)
            min_sq_distances = sq_distances.min(axis=1)  # (n_samples,)

            # Convert to probabilities — farther points are more likely to be picked
            probabilities = min_sq_distances / min_sq_distances.sum()

            # Weighted random selection
            next_idx = self.random_state.choice(n_samples, p=probabilities)
            next_centroid = X[next_idx][np.newaxis, :]  # (1, n_features)
            self.cluster_centers_ = np.vstack(
                [self.cluster_centers_, next_centroid]
            )  # (k+1, n_features)

        return self

    def _initialize_centroids(self, X):
        self._init_centroids_plusplus(X)
